from enum import Enum

BOARD_WIDTH = 700
BOARD_HEIGHT = 700
SCREEN_WIDTH = BOARD_WIDTH
SCREEN_HEIGHT = BOARD_HEIGHT + 100
ROWS = 8
COLS = 8
SQUARE_SIZE = BOARD_WIDTH // COLS

USE_NEURAL_NETWORK = False
GENERATE_TRAINING_DATA = False

class PlayerMode(Enum):
    HUMAN = 0
    BOT = 1
    AGENT = 2

class NeuralNetwork(Enum):
    NEURAL_NETWORK_STARTER = 0  
    NEURAL_NETWORK_WITH_CURRENT_PLAYER = 1  

PLAYER_1 = PlayerMode(2)
PLAYER_2 = PlayerMode(1)

AGENT_1_NEURAL_NETWORK = None
AGENT_2_NEURAL_NETWORK = None

BOT_MOVE_TIME = 2000